config/routes.rb
Rails.application.routes.draw do
  resources :markers
  root to: 'markers#index'
end

app/models/marker.rb
class Marker < ActiveRecord::Base

  # Watermarking image with another image using Imagemagick 'composite', 'watermark' and 'dissolve'.
  require "rubygems"
  require "rmagick"
  include Magick

  def define_gravity(location)
    @gravity =
        case location
          when "Upper-Left"
            Magick::NorthWestGravity
          when "Upper-Right"
            Magick::NorthEastGravity
          when "Lower-Left"
            Magick::SouthWestGravity
          when "Lower-Right"
            Magick::SouthEastGravity
          else
            Magick::SouthEastGravity
        end
  end

  def set_filename_and_extension(filename)
    @filename  = File.basename(filename, ".*")
    @extension = File.extname(filename)
  end

  def get_file_data(file)
    return Magick::Image.from_blob(file.read).first
  end

  def watermark(params)
    define_gravity(params[:location])
    set_filename_and_extension(params[:source].original_filename)

    img                   = get_file_data(params[:source])
    mark                  = get_file_data(params[:watermark])
    mark.background_color = "Transparent" # set the canvas to transparent
    scale_value           = (params[:size].to_f / 100)
    watermark             = mark.resize_to_fit(img.rows * scale_value, img.columns * scale_value) # resize the watermark to 60% of the image we want to watermark
    img1                  = img.composite(watermark, @gravity, 25, 25, Magick::OverCompositeOp)
    name                  = "#{@filename}_#{Time.now.to_i}#{@extension}"
    img1.write(Rails.root.join('public', "#{name}")) # save the watermarked image
    path_to_file = Rails.root.join('public', "#{name}")
    return path_to_file

    # Read the image in the memory with RMagick
    #   puts "What is the image file you want to watermark?"
    #   puts "Drag and drop the file here or enter the full path to the image"
    #   path = gets.chomp
    #
    #   path = "/Users/i851546/Screen Shot 2017-09-14 at 12.45.40.png" if path.length == 0

    # the original image was in jpg format
    # need to make the white background color transparent
    # also changed the format to png since JPG does not support transparency.
    # run the command below to create an image with transparent background using ImageMagick
    # convert cc.png -transparent white -fuzz 2% watermark.png

    # puts "What watermark file do you want to use?"
    # puts "Drag and drop the file here or enter the full path to the image"
    # watermark_path = gets.chomp
    #
    # watermark_path = "/Users/i851546/Documents/SAP/sap_anywhere_logo.png" if watermark_path.length == 0


    # if we do not specify 'background_color' on 'mark' then on rotation the background color will be black.
    # we want it to be transparent.

    # rotate this mark by 45 degrees anticlockwise (optional)
    # watermark.rotate!(-45)

    # using composite
    # place the watermark in the center of the image
    # default 'compose over' overlays the watermark on the background image
    # SoftLightCompositeOp darkens or lightens the colors, dependent on the source color value.
    # If the source color is lighter than 0.5, the destination is lightened.
    # If the source color is darker than 0.5, the destination is darkened, as if it were burned in.
    # The degree of darkening or lightening is proportional to the difference between the source color and 0.5.
    # If it is equal to 0.5, the destination is unchanged.
    # Painting with pure black or white produces a distinctly darker or lighter area, but does not result in pure black or white.
    # img1 = img.composite(watermark, Magick::SouthEastGravity, Magick::SoftLightCompositeOp)

    # using overlay
    # We define which image to composite (img is the source image we want watermarked), then we define where that watermark should start
    # finally we say that the watermark should be composed over the top of the source image with OverCompositeOp


    # using watermark
    # place the watermark in the center of the image with gravity
    # watermark the image with 20% brightness and 30% saturation
    # img2 = img.watermark(watermark, 0.2, 0.3, Magick::CenterGravity)
    # save the watermarked image
    # img2.write("/home/aditya/Pictures/wm_old_england_pic_image_watermark.jpg")

    # using dissolve
    # add watermark with 40% opacity for watermark, 100% opacity for image and position is center
    # img3 = img.dissolve(watermark, 0.4, 1, Magick::CenterGravity)
    # save the watermarked image
    # img3.write("/home/aditya/Pictures/wm_old_england_pic_image_dissolve.jpg")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  layout false
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  # GET /markers
  # GET /markers.json
  def index
    @marker = Marker.new
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    file        = Marker.new
    watermarked = file.watermark(marker_params)

    send_file(watermarked)
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: 'Marker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_marker
    @marker = Marker.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def marker_params
    params.fetch(:marker, {})
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Watermarker" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Watermarker" %>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_for(@marker) do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

      <ul>
      <% @marker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form' %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>Watermarking Made Easy!</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
   (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-5409055050585472",
    enable_page_level_ads: true
  });
</script>
<meta name="google-site-verification" content="0NtVPjEtg-Zlty2JBH9tUgYpxF4KkMm--ykbdS6fRio" />
</head>

<body>

  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <a class="navbar-brand" href="#">The Watermarker</a>
  </nav>

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h3 class="display-4">Hello, h00man!</h3>
      <p>You need to add your corporate logo or some other watermark to an image, and you don't have an image editing application handy, right?  Select the source image first, then the logo image, then click the green button and get your watermarked image back!  This utility was created to help people online do one thing quickly and FOR FREE, but it would be great if you click on one of the ads that you see.</p>
      <p><a class="btn btn-primary btn-lg" href="http://misaiato.blogspot.com" role="button">About me &raquo;</a></p>
      <p>I <a href="http://tgmerritt.github.io/">like to write small software applications</a> to demonstrate different technologies.  This application uses Ruby on Rails and runs on top of Amazon's Elastic Beanstalk.  It leverages the ImageMagick library to manipulate images which is how we end up with this watermarker web app.  This is a perfect app when you're not on your machine and need to quickly get a watermarked image to someone - you might get the images via email and work off of a machine in a hotel lobby - you can still complete the task!  I hope you enjoy it.</p>

      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <ins class="adsbygoogle"
      style="display:block; text-align:center;"
      data-ad-layout="in-article"
      data-ad-format="fluid"
      data-ad-client="ca-pub-5409055050585472"
      data-ad-slot="1549010030"></ins>
      <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
     </script>

     <p>I'll be adding additional functions to the watermarker over time - like overlay, diffused overlay, rotation on an axis, centering, and other types of watermarking time permitting.  Use this tool as much as you'd like - please share the tool with others.</p>  
   </div>
 </div>

 <div class="container">
  <%= form_for @marker do |m| %>
  <div class="row">
    <div class="col-md-4">
      <h2>Source Image</h2>

      <p>Select the file that you want to add a watermark to from the select box below.</p>
      <%= m.file_field :source %>
    </div>
    <div class="col-md-4">
      <h2>Watermark Image</h2>

      <p>Select the image you want to use as your watermark from the select box below. This is typically your
      corporate logo or some other text that will layer on top of the source image. </p>
      <%= m.file_field :watermark %>
    </div>
    <div class="col-md-4">
      <h2>Options</h2>
      <%= label(:marker, :watermark_position) %>
      <%= select_tag :location, options_for_select(["Upper-Left", "Upper-Right", "Lower-Left", "Lower-Right"], "Lower-Right"), class: "custom-select", name: "marker[location]", id: "marker_location" %>
      <p></p>
      <%= label(:marker, "Scale watermark down by (%)") %>
      <%= select_tag :size, options_for_select((5..100).step(5), 60), class: "custom-select", name: "marker[size]", id: "marker_size"  %>
    </div>
  </div>
  <div class="row" style="padding-top: 45px">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <h2>Do Magick!</h2>

      <p>Click the button below to watermark your image</p>

      <p class="center"><%= m.submit "Do Magick!", class: "btn btn-success" %>
      </div>

    </div>
  </div>
  <% end %>

  <hr>

  <footer>
    <p>&copy; Tyler 2017</p>
  </footer>
</div>

  <!-- Bootstrap core JavaScript
   ================================================== -->
   <!-- Placed at the end of the document so the pages load faster -->
   <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
   <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
   <script src="../../dist/js/bootstrap.min.js"></script>
   <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
   <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
 </body>
 </html>

app/views/markers/new.html.erb
<h1>New Marker</h1>

<%= render 'form' %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>